temp changes

diff --git a/.github/workflows/functional-test.yaml b/.github/workflows/functional-test.yaml
--- a/.github/workflows/functional-test.yaml
+++ b/.github/workflows/functional-test.yaml
@@ -401,179 +401,179 @@ jobs:
       - uses: azure/setup-helm@v3
         with:
           version: ${{ env.HELM_VER }}
-      - name: Create KinD cluster
-        run: |
-          curl -sSLo "kind" "https://github.com/kubernetes-sigs/kind/releases/download/${{ env.KIND_VER }}/kind-linux-amd64"
-          chmod +x ./kind
+      # - name: Create KinD cluster
+      #   run: |
+      #     curl -sSLo "kind" "https://github.com/kubernetes-sigs/kind/releases/download/${{ env.KIND_VER }}/kind-linux-amd64"
+      #     chmod +x ./kind
 
-          # Populate the following environment variables for Azure workload identity from secrets.
-          # AZURE_OIDC_ISSUER_PUBLIC_KEY
-          # AZURE_OIDC_ISSUER_PRIVATE_KEY
-          # AZURE_OIDC_ISSUER
-          eval "export $(echo "${{ secrets.FUNCTEST_AZURE_OIDC_JSON }}" | jq -r 'to_entries | map("\(.key)=\(.value)") | @sh')"
+      #     # Populate the following environment variables for Azure workload identity from secrets.
+      #     # AZURE_OIDC_ISSUER_PUBLIC_KEY
+      #     # AZURE_OIDC_ISSUER_PRIVATE_KEY
+      #     # AZURE_OIDC_ISSUER
+      #     eval "export $(echo "${{ secrets.FUNCTEST_AZURE_OIDC_JSON }}" | jq -r 'to_entries | map("\(.key)=\(.value)") | @sh')"
 
-          AUTHKEY=$(echo -n "${{ github.actor }}:${{ secrets.GH_RAD_CI_BOT_PAT }}" | base64)
-          echo "{\"auths\":{\"ghcr.io\":{\"auth\":\"${AUTHKEY}\"}}}" > "./ghcr_secret.json"
+      #     AUTHKEY=$(echo -n "${{ github.actor }}:${{ secrets.GH_RAD_CI_BOT_PAT }}" | base64)
+      #     echo "{\"auths\":{\"ghcr.io\":{\"auth\":\"${AUTHKEY}\"}}}" > "./ghcr_secret.json"
 
-          # Create KinD cluster with OIDC Issuer keys
-          echo $AZURE_OIDC_ISSUER_PUBLIC_KEY | base64 -d > sa.pub
-          echo $AZURE_OIDC_ISSUER_PRIVATE_KEY | base64 -d > sa.key
-          cat <<EOF | ./kind create cluster --name radius --config=-
-          kind: Cluster
-          apiVersion: kind.x-k8s.io/v1alpha4
-          nodes:
-          - role: control-plane
-            extraMounts:
-              - hostPath: ./sa.pub
-                containerPath: /etc/kubernetes/pki/sa.pub
-              - hostPath: ./sa.key
-                containerPath: /etc/kubernetes/pki/sa.key
-              - hostPath: ./ghcr_secret.json
-                containerPath: /var/lib/kubelet/config.json
-            kubeadmConfigPatches:
-            - |
-              kind: ClusterConfiguration
-              apiServer:
-                extraArgs:
-                  service-account-issuer: $AZURE_OIDC_ISSUER
-                  service-account-key-file: /etc/kubernetes/pki/sa.pub
-                  service-account-signing-key-file: /etc/kubernetes/pki/sa.key
-              controllerManager:
-                extraArgs:
-                  service-account-private-key-file: /etc/kubernetes/pki/sa.key
-          EOF
-      - name: Install dapr into cluster
-        run: |
-          wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash -s ${{ env.DAPR_VER }}
-          dapr init -k --wait --timeout 600 --runtime-version ${{ env.DAPR_VER }}
-      - name: Install Azure Keyvault CSI driver chart
-        run: |
-          helm repo add csi-secrets-store-provider-azure https://azure.github.io/secrets-store-csi-driver-provider-azure/charts
-          helm install csi csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --version ${{ env.AZURE_KEYVAULT_CSI_DRIVER_VER }}
-      - name: Install azure workload identity webhook chart
-        run: |
-          helm repo add azure-workload-identity https://azure.github.io/azure-workload-identity/charts
-          helm install workload-identity-webhook azure-workload-identity/workload-identity-webhook --namespace radius-default --create-namespace --version ${{ env.AZURE_WORKLOAD_IDENTITY_WEBHOOK_VER }} --set azureTenantID=${{ secrets.INTEGRATION_TEST_TENANT_ID }}
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v2
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - name: Download Bicep
-        run: |
-          chmod +x ./bin/rad
-          export PATH=$GITHUB_WORKSPACE/bin:$PATH
-          which rad || { echo "cannot find rad"; exit 1; }
-          rad bicep download
-          rad version
-      - name: Install gotestsum (test reporting tool)
-        run: |
-          go install gotest.tools/gotestsum@v${{ env.GOTESTSUM_VER }}
-      - uses: marocchino/sticky-pull-request-comment@v2
-        if: failure() && env.PR_NUMBER != ''
-        continue-on-error: true
-        with:
-          GITHUB_TOKEN: ${{ steps.get_installation_token.outputs.token }}
-          header: teststatus-${{ github.run_id }}
-          number: ${{ env.PR_NUMBER }}
-          append: true
-          message: |
-            :x: Test tool installation for ${{ matrix.name }} failed. Please check [the logs](${{ env.ACTION_LINK }}) for more details
-      - name: Install Radius
-        run: |
-          export PATH=$GITHUB_WORKSPACE/bin:$PATH
-          which rad || { echo "cannot find rad"; exit 1; }
+      #     # Create KinD cluster with OIDC Issuer keys
+      #     echo $AZURE_OIDC_ISSUER_PUBLIC_KEY | base64 -d > sa.pub
+      #     echo $AZURE_OIDC_ISSUER_PRIVATE_KEY | base64 -d > sa.key
+      #     cat <<EOF | ./kind create cluster --name radius --config=-
+      #     kind: Cluster
+      #     apiVersion: kind.x-k8s.io/v1alpha4
+      #     nodes:
+      #     - role: control-plane
+      #       extraMounts:
+      #         - hostPath: ./sa.pub
+      #           containerPath: /etc/kubernetes/pki/sa.pub
+      #         - hostPath: ./sa.key
+      #           containerPath: /etc/kubernetes/pki/sa.key
+      #         - hostPath: ./ghcr_secret.json
+      #           containerPath: /var/lib/kubelet/config.json
+      #       kubeadmConfigPatches:
+      #       - |
+      #         kind: ClusterConfiguration
+      #         apiServer:
+      #           extraArgs:
+      #             service-account-issuer: $AZURE_OIDC_ISSUER
+      #             service-account-key-file: /etc/kubernetes/pki/sa.pub
+      #             service-account-signing-key-file: /etc/kubernetes/pki/sa.key
+      #         controllerManager:
+      #           extraArgs:
+      #             service-account-private-key-file: /etc/kubernetes/pki/sa.key
+      #     EOF
+      # - name: Install dapr into cluster
+      #   run: |
+      #     wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash -s ${{ env.DAPR_VER }}
+      #     dapr init -k --wait --timeout 600 --runtime-version ${{ env.DAPR_VER }}
+      # - name: Install Azure Keyvault CSI driver chart
+      #   run: |
+      #     helm repo add csi-secrets-store-provider-azure https://azure.github.io/secrets-store-csi-driver-provider-azure/charts
+      #     helm install csi csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --version ${{ env.AZURE_KEYVAULT_CSI_DRIVER_VER }}
+      # - name: Install azure workload identity webhook chart
+      #   run: |
+      #     helm repo add azure-workload-identity https://azure.github.io/azure-workload-identity/charts
+      #     helm install workload-identity-webhook azure-workload-identity/workload-identity-webhook --namespace radius-default --create-namespace --version ${{ env.AZURE_WORKLOAD_IDENTITY_WEBHOOK_VER }} --set azureTenantID=${{ secrets.INTEGRATION_TEST_TENANT_ID }}
+      # - name: Login to GitHub Container Registry
+      #   uses: docker/login-action@v2
+      #   with:
+      #     registry: ghcr.io
+      #     username: ${{ github.actor }}
+      #     password: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Download Bicep
+      #   run: |
+      #     chmod +x ./bin/rad
+      #     export PATH=$GITHUB_WORKSPACE/bin:$PATH
+      #     which rad || { echo "cannot find rad"; exit 1; }
+      #     rad bicep download
+      #     rad version
+      # - name: Install gotestsum (test reporting tool)
+      #   run: |
+      #     go install gotest.tools/gotestsum@v${{ env.GOTESTSUM_VER }}
+      # - uses: marocchino/sticky-pull-request-comment@v2
+      #   if: failure() && env.PR_NUMBER != ''
+      #   continue-on-error: true
+      #   with:
+      #     GITHUB_TOKEN: ${{ steps.get_installation_token.outputs.token }}
+      #     header: teststatus-${{ github.run_id }}
+      #     number: ${{ env.PR_NUMBER }}
+      #     append: true
+      #     message: |
+      #       :x: Test tool installation for ${{ matrix.name }} failed. Please check [the logs](${{ env.ACTION_LINK }}) for more details
+      # - name: Install Radius
+      #   run: |
+      #     export PATH=$GITHUB_WORKSPACE/bin:$PATH
+      #     which rad || { echo "cannot find rad"; exit 1; }
 
-          echo "*** Installing Radius to Kubernetes ***"
-          rad install kubernetes \
-            --chart ${{ env.RADIUS_CHART_LOCATION }} \
-            --set rp.image=${{ env.CONTAINER_REGISTRY }}/applications-rp,rp.tag=${{ env.REL_VERSION }},controller.image=${{ env.CONTAINER_REGISTRY }}/controller,controller.tag=${{ env.REL_VERSION }},ucp.image=${{ env.CONTAINER_REGISTRY }}/ucpd,ucp.tag=${{ env.REL_VERSION }},de.image=${{ env.DE_IMAGE }},de.tag=${{ env.DE_TAG }}
+      #     echo "*** Installing Radius to Kubernetes ***"
+      #     rad install kubernetes \
+      #       --chart ${{ env.RADIUS_CHART_LOCATION }} \
+      #       --set rp.image=${{ env.CONTAINER_REGISTRY }}/applications-rp,rp.tag=${{ env.REL_VERSION }},controller.image=${{ env.CONTAINER_REGISTRY }}/controller,controller.tag=${{ env.REL_VERSION }},ucp.image=${{ env.CONTAINER_REGISTRY }}/ucpd,ucp.tag=${{ env.REL_VERSION }},de.image=${{ env.DE_IMAGE }},de.tag=${{ env.DE_TAG }}
 
-          echo "*** Create workspace, group and environment for test ***"
-          rad workspace create kubernetes
-          rad group create kind-radius
-          rad group switch kind-radius
+      #     echo "*** Create workspace, group and environment for test ***"
+      #     rad workspace create kubernetes
+      #     rad group create kind-radius
+      #     rad group switch kind-radius
 
-          # The functional test is designed to use default namespace. So you must create the environment for default namespace.
-          rad env create kind-radius --namespace default
-          rad env switch kind-radius
+      #     # The functional test is designed to use default namespace. So you must create the environment for default namespace.
+      #     rad env create kind-radius --namespace default
+      #     rad env switch kind-radius
 
-          echo "*** Configuring Azure provider ***"
-          rad env update kind-radius --azure-subscription-id ${{ secrets.INTEGRATION_TEST_SUBSCRIPTION_ID }} \
-            --azure-resource-group ${{ env.AZURE_TEST_RESOURCE_GROUP }}
-          rad credential register azure --client-id ${{ secrets.INTEGRATION_TEST_SP_APP_ID }} \
-            --client-secret ${{ secrets.INTEGRATION_TEST_SP_PASSWORD }} \
-            --tenant-id ${{ secrets.INTEGRATION_TEST_TENANT_ID }}
+      #     echo "*** Configuring Azure provider ***"
+      #     rad env update kind-radius --azure-subscription-id ${{ secrets.INTEGRATION_TEST_SUBSCRIPTION_ID }} \
+      #       --azure-resource-group ${{ env.AZURE_TEST_RESOURCE_GROUP }}
+      #     rad credential register azure --client-id ${{ secrets.INTEGRATION_TEST_SP_APP_ID }} \
+      #       --client-secret ${{ secrets.INTEGRATION_TEST_SP_PASSWORD }} \
+      #       --tenant-id ${{ secrets.INTEGRATION_TEST_TENANT_ID }}
 
-          echo "*** Configuring AWS provider ***"
-          rad env update kind-radius --aws-region ${{ env.AWS_REGION }} --aws-account-id ${{ secrets.FUNCTEST_AWS_ACCOUNT_ID }}
-          rad credential register aws \
-            --access-key-id ${{ secrets.FUNCTEST_AWS_ACCESS_KEY_ID }} --secret-access-key ${{ secrets.FUNCTEST_AWS_SECRET_ACCESS_KEY }}
-      - uses: marocchino/sticky-pull-request-comment@v2
-        if: failure() && env.PR_NUMBER != ''
-        continue-on-error: true
-        with:
-          GITHUB_TOKEN: ${{ steps.get_installation_token.outputs.token }}
-          header: teststatus-${{ github.run_id }}
-          number: ${{ env.PR_NUMBER }}
-          append: true
-          message: |
-            :x: Failed to install Radius for ${{ matrix.name }} functional test. Please check [the logs](${{ env.ACTION_LINK }}) for more details
-      - name: Publish Terraform test recipes
-        run: |
-          make publish-test-terraform-recipes
-      - name: Run functional tests
-        run: |
-          # Ensure rad cli is in path before running tests.
-          export PATH=$GITHUB_WORKSPACE/bin:$PATH
-          cd $GITHUB_WORKSPACE
+      #     echo "*** Configuring AWS provider ***"
+      #     rad env update kind-radius --aws-region ${{ env.AWS_REGION }} --aws-account-id ${{ secrets.FUNCTEST_AWS_ACCOUNT_ID }}
+      #     rad credential register aws \
+      #       --access-key-id ${{ secrets.FUNCTEST_AWS_ACCESS_KEY_ID }} --secret-access-key ${{ secrets.FUNCTEST_AWS_SECRET_ACCESS_KEY }}
+      # - uses: marocchino/sticky-pull-request-comment@v2
+      #   if: failure() && env.PR_NUMBER != ''
+      #   continue-on-error: true
+      #   with:
+      #     GITHUB_TOKEN: ${{ steps.get_installation_token.outputs.token }}
+      #     header: teststatus-${{ github.run_id }}
+      #     number: ${{ env.PR_NUMBER }}
+      #     append: true
+      #     message: |
+      #       :x: Failed to install Radius for ${{ matrix.name }} functional test. Please check [the logs](${{ env.ACTION_LINK }}) for more details
+      # - name: Publish Terraform test recipes
+      #   run: |
+      #     make publish-test-terraform-recipes
+      # - name: Run functional tests
+      #   run: |
+      #     # Ensure rad cli is in path before running tests.
+      #     export PATH=$GITHUB_WORKSPACE/bin:$PATH
+      #     cd $GITHUB_WORKSPACE
 
-          which rad || { echo "cannot find rad"; exit 1; }
+      #     which rad || { echo "cannot find rad"; exit 1; }
 
-          # Populate the following test environment variables from JSON secret.
-          # AZURE_MONGODB_RESOURCE_ID
-          # AZURE_COSMOS_MONGODB_ACCOUNT_ID
-          # AZURE_TABLESTORAGE_RESOURCE_ID
-          # AZURE_SERVICEBUS_RESOURCE_ID
-          # AZURE_REDIS_RESOURCE_ID
-          # AZURE_MSSQL_RESOURCE_ID
-          # AZURE_MSSQL_USERNAME
-          # AZURE_MSSQL_PASSWORD
-          eval "export $(echo "${{ secrets.FUNCTEST_PREPROVISIONED_RESOURCE_JSON }}" | jq -r 'to_entries | map("\(.key)=\(.value)") | @sh')"
+      #     # Populate the following test environment variables from JSON secret.
+      #     # AZURE_MONGODB_RESOURCE_ID
+      #     # AZURE_COSMOS_MONGODB_ACCOUNT_ID
+      #     # AZURE_TABLESTORAGE_RESOURCE_ID
+      #     # AZURE_SERVICEBUS_RESOURCE_ID
+      #     # AZURE_REDIS_RESOURCE_ID
+      #     # AZURE_MSSQL_RESOURCE_ID
+      #     # AZURE_MSSQL_USERNAME
+      #     # AZURE_MSSQL_PASSWORD
+      #     eval "export $(echo "${{ secrets.FUNCTEST_PREPROVISIONED_RESOURCE_JSON }}" | jq -r 'to_entries | map("\(.key)=\(.value)") | @sh')"
 
-          make test-functional-${{ matrix.name }}
-        env:
-          DOCKER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
-          TEST_TIMEOUT: ${{ env.FUNCTIONALTEST_TIMEOUT }}
-          RADIUS_CONTAINER_LOG_PATH: ${{ github.workspace }}/${{ env.RADIUS_CONTAINER_LOG_BASE }}
-          AWS_ACCESS_KEY_ID: ${{ secrets.FUNCTEST_AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.FUNCTEST_AWS_SECRET_ACCESS_KEY }}
-          AWS_REGION: ${{ env.AWS_REGION }}
-          RADIUS_SAMPLES_REPO_ROOT: ${{ github.workspace }}/samples
-          # Test_MongoDB_Recipe_Parameters is using the following environment variable.
-          INTEGRATION_TEST_RESOURCE_GROUP_NAME: ${{ env.AZURE_TEST_RESOURCE_GROUP }}
-          BICEP_RECIPE_REGISTRY: ${{ env.BICEP_RECIPE_REGISTRY }}
-          BICEP_RECIPE_TAG_VERSION: ${{ env.BICEP_RECIPE_TAG_VERSION }}
-      - uses: azure/setup-kubectl@v3
-        if: always()
-        with:
-          version: ${{ env.KUBECTL_VER }}
-      - name: Collect Pod details
-        if: always()
-        run: |
-          POD_STATE_LOG_FILENAME='${{ env.RADIUS_CONTAINER_LOG_BASE }}/${{ matrix.name }}-tests-pod-states.log'
-          mkdir -p $(dirname $POD_STATE_LOG_FILENAME)
-          echo "kubectl get pods -A" >> $POD_STATE_LOG_FILENAME
-          kubectl get pods -A >> $POD_STATE_LOG_FILENAME
-          echo "kubectl describe pods -A" >> $POD_STATE_LOG_FILENAME
-          kubectl describe pods -A >> $POD_STATE_LOG_FILENAME
-      - name: Upload container logs
-        if: always()
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ matrix.name }}_container_logs
-          path: ./${{ env.RADIUS_CONTAINER_LOG_BASE }}
+      #     make test-functional-${{ matrix.name }}
+      #   env:
+      #     DOCKER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
+      #     TEST_TIMEOUT: ${{ env.FUNCTIONALTEST_TIMEOUT }}
+      #     RADIUS_CONTAINER_LOG_PATH: ${{ github.workspace }}/${{ env.RADIUS_CONTAINER_LOG_BASE }}
+      #     AWS_ACCESS_KEY_ID: ${{ secrets.FUNCTEST_AWS_ACCESS_KEY_ID }}
+      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.FUNCTEST_AWS_SECRET_ACCESS_KEY }}
+      #     AWS_REGION: ${{ env.AWS_REGION }}
+      #     RADIUS_SAMPLES_REPO_ROOT: ${{ github.workspace }}/samples
+      #     # Test_MongoDB_Recipe_Parameters is using the following environment variable.
+      #     INTEGRATION_TEST_RESOURCE_GROUP_NAME: ${{ env.AZURE_TEST_RESOURCE_GROUP }}
+      #     BICEP_RECIPE_REGISTRY: ${{ env.BICEP_RECIPE_REGISTRY }}
+      #     BICEP_RECIPE_TAG_VERSION: ${{ env.BICEP_RECIPE_TAG_VERSION }}
+      # - uses: azure/setup-kubectl@v3
+      #   if: always()
+      #   with:
+      #     version: ${{ env.KUBECTL_VER }}
+      # - name: Collect Pod details
+      #   if: always()
+      #   run: |
+      #     POD_STATE_LOG_FILENAME='${{ env.RADIUS_CONTAINER_LOG_BASE }}/${{ matrix.name }}-tests-pod-states.log'
+      #     mkdir -p $(dirname $POD_STATE_LOG_FILENAME)
+      #     echo "kubectl get pods -A" >> $POD_STATE_LOG_FILENAME
+      #     kubectl get pods -A >> $POD_STATE_LOG_FILENAME
+      #     echo "kubectl describe pods -A" >> $POD_STATE_LOG_FILENAME
+      #     kubectl describe pods -A >> $POD_STATE_LOG_FILENAME
+      # - name: Upload container logs
+      #   if: always()
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: ${{ matrix.name }}_container_logs
+      #     path: ./${{ env.RADIUS_CONTAINER_LOG_BASE }}
       - uses: LouisBrunner/checks-action@v1.6.1
         if: always()
         with:
